version: "3"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3010:3010'
    volumes:
      - './frontend:/frontend'
    command: /bin/sh -c "yarn start"
    depends_on:
        - db
        - api
    env_file:
      - ./frontend/.env
    tty: true
    stdin_open: true

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - '5432:5432'
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    volumes:
      - './api:/api'
    ports:
      - '3000:3000'

